hacker_reattempt = '''
Your exploit failed the test case. The output of forge test is: \n```{forge_test_output}```\n. Based on this, reattempt the solution and write a new exploit.
'''
